# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to=b'images/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to=b'images/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to=b'images/')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to=b'images/')),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to=b'images/')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='anio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='asegurado',
            field=models.IntegerField(choices=[(1, b'Si'), (0, b'No')], default=1),
        ),
        migrations.AddField(
            model_name='caso',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caso',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='kilometros',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='marca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='modelo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='observaciones',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caso',
            name='personal',
            field=models.IntegerField(choices=[(1, b'Si'), (0, b'No')], default=1),
        ),
        migrations.AddField(
            model_name='caso',
            name='placa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='tipo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='transmision',
            field=models.IntegerField(choices=[(1, b'Mecanico'), (0, b'Automatico')], default=1),
        ),
        migrations.AddField(
            model_name='caso',
            name='vin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avance',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.Caso'),
        ),
        migrations.AddField(
            model_name='caso',
            name='aseguradora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='casos.Aseguradora'),
            preserve_default=False,
        ),
    ]
