# Generated by Django 2.0.3 on 2018-03-13 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aseguradoras', to='casos.Aseguradora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='anio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='asegurado',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='caso',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caso',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='kilometros',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='marca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='modelo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='observaciones',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caso',
            name='personal',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='caso',
            name='placa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='tipo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='transmision',
            field=models.IntegerField(choices=[(1, 'Mecanico'), (0, 'Automatico')], default=1),
        ),
        migrations.AddField(
            model_name='caso',
            name='vin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='estado_caso_id',
            field=models.IntegerField(choices=[(1, 'Recibido'), (2, 'En Proceso'), (3, 'Terminando')], default=1),
        ),
        migrations.AddField(
            model_name='avance',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.Caso'),
        ),
        migrations.AddField(
            model_name='caso',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='casos.Aseguradora'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioaseguradora',
            unique_together={('aseguradora', 'usuario')},
        ),
    ]
