# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casos', '0002_auto_20171102_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aseguradoras', to='casos.Aseguradora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='avance',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='imagen_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='asegurado',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='caso',
            name='personal',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='caso',
            name='transmision',
            field=models.IntegerField(choices=[(1, 'Mecanico'), (0, 'Automatico')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioaseguradora',
            unique_together=set([('aseguradora', 'usuario')]),
        ),
    ]
