# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_auto_20171106_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='casos.Aseguradora'),
        ),
    ]
